// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgR1bgNG6v0ThZ3NZl2rxSFX6Hh9G5EPU',
    appId: '1:536218224060:web:f6e99b15d669afe0cdd7b9',
    messagingSenderId: '536218224060',
    projectId: 'sfirebase-a8d95',
    authDomain: 'sfirebase-a8d95.firebaseapp.com',
    storageBucket: 'sfirebase-a8d95.appspot.com',
    measurementId: 'G-TGFDH1205T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnEO9oUCNfz145JE1G78N9NElvSKXKMvg',
    appId: '1:536218224060:android:8a077d34136782bacdd7b9',
    messagingSenderId: '536218224060',
    projectId: 'sfirebase-a8d95',
    storageBucket: 'sfirebase-a8d95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7XyjXUglaPYm593tQz9-wco-OWL2qPRk',
    appId: '1:536218224060:ios:ac46787921fb7621cdd7b9',
    messagingSenderId: '536218224060',
    projectId: 'sfirebase-a8d95',
    storageBucket: 'sfirebase-a8d95.appspot.com',
    iosBundleId: 'com.example.wallpaperApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7XyjXUglaPYm593tQz9-wco-OWL2qPRk',
    appId: '1:536218224060:ios:ac46787921fb7621cdd7b9',
    messagingSenderId: '536218224060',
    projectId: 'sfirebase-a8d95',
    storageBucket: 'sfirebase-a8d95.appspot.com',
    iosBundleId: 'com.example.wallpaperApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgR1bgNG6v0ThZ3NZl2rxSFX6Hh9G5EPU',
    appId: '1:536218224060:web:931f93a7ec33cf54cdd7b9',
    messagingSenderId: '536218224060',
    projectId: 'sfirebase-a8d95',
    authDomain: 'sfirebase-a8d95.firebaseapp.com',
    storageBucket: 'sfirebase-a8d95.appspot.com',
    measurementId: 'G-DJR6J49ECG',
  );
}
